version: '3'
services:
  demo-app:
    container_name: demo-app
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
    depends_on:
      - db
      - mongo

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
